name: pokedex_colaboraapp
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
#HTTP 
  dio: ^5.2.1+1   

#Local Storage Management 
  shared_preferences: ^2.2.0
  
#Models/json Management
  json_serializable: ^6.7.1
  json_annotation: ^4.8.1

#Routes/Dependecy Injection 
  flutter_modular: ^5.0.3

#State Management 
  mobx: ^2.1.3
  flutter_mobx: ^2.0.6+5

#UI  
  flutter_svg: ^2.0.7
  palette_generator: ^0.3.3+2
  shimmer_animation: ^2.1.0+1
  show_up_animation: ^2.0.0
  
  
  
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  mobx_codegen: ^2.1.1

flutter:
  uses-material-design: true
  assets:
    - assets/background_objects/pokemons/
    - assets/logo/
    - assets/icons/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 900

        - asset: assets/fonts/Roboto-Italic.ttf
          style: italic

        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 700

        - asset: assets/fonts/Roboto-Regular.ttf
          weight: 500