name: pokedex_colaboraapp
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
#HTTP 
  dio: ^5.2.1+1   
#Routes/Dependecy Injection 
  flutter_modular: ^5.0.3

  json_serializable: ^6.7.1
  json_annotation: ^4.8.1

#State Management 
  mobx: ^2.1.3
  flutter_mobx: ^2.0.6+5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  mobx_codegen: ^2.1.1

flutter:
  uses-material-design: true
