name: Build android files

on:
  push:
    branches:
      - "main"
  ## uncomment this line to can run the action without need push
  #workflow_dispatch:

jobs:
  build:
    # This job will run on ubuntu virtual machine
    runs-on: ubuntu-latest
    # runs-on: macos-latest
    steps:


      # Setup Java environment in order to build the Android app.
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: "12.x"

      # Setup the flutter environment.
      - name: Setup Flutter
        uses: subosito/flutter-action@v2.11.0
        with:
          channel: "stable" # 'dev', 'alpha', default to: 'stable'
          flutter-version: "3.10.0" # you can also specify exact version of flutter

      - name: Cache pub dependencies
        uses: actions/cache@v2
        with:
          path: ${{ env.FLUTTER_HOME }}/.pub-cache
          key: ${{ runner.os }}-pub-${{ hashFiles('**/pubspec.lock') }}
          restore-keys: ${{ runner.os }}-pub-
        
      - name: Download pub dependencies
        run: flutter pub get

      - name: Build Android APK
        run: flutter build apk
      
      - name: Upload APK
        uses: actions/upload-artifact@v3.1.3
        with:
          name: bundle release
          #path: build/app/outputs/bundle/devRelease/app-dev-release.aab

      - name: Build Android AppBundle
        run: flutter build appbundle

      - name: Upload a AAB
        uses: actions/upload-artifact@v3.1.3
        with:
          name: bundle release
          #path: build/app/outputs/bundle/devRelease/app-dev-release.aab
